openapi: 3.0.0
info:
  title: linkshrt API
  version: 1.0.0
  description: URL shortener with JWT authentication
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '201':
          description: User created
        '400':
          description: Invalid input
  /login:
    post:
      summary: Login and get token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: StatusOk
        '400':
          description: Invalid input
        '401':
          description: Unathorized
  /shorten:
    post:
      summary: Create short link
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenRequest'
      responses:
        '201':
          description: Shorten link created
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
  /{code}:
    get:
      summary: Redirect
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect
        '404':
          description: Not Found
components:
  schemas:
    AuthRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required: [login, password]
    ShortenRequest:
      type: object
      properties:
        url:
          type: string
      required: [url]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT